version: "3"

services:
  ddns:
    container_name: dynu
    image: beringbullet/dynu
    environment:
      - DYN_HOSTNAME=${DYN_HOSTNAME}
      - DYN_USER=${DYN_USER}
      - DYN_PASS=${DYN_PASS}
    restart: always