version: "2.3"
services:
  emby:
    image: emby/embyserver
    container_name: embyserver
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - /mnt/disk1/emby/config:/config
      - /mnt/disk1/video/movies:/movies
      - /mnt/disk1/video/tvshows:/tvshows
      - /mnt/disk1/video/workouts:/workouts
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
