FROM python:3-alpine

RUN apk update

ADD ./app/ /
RUN apk add \
        libffi-dev \
        musl-dev \
        gcc \
        && rm -rf /var/cache/apk/* \
        && pip install -r requirements.txt \
        && apk del --purge libffi-dev musl-dev gcc

CMD [ "python", "./app.py" ]